server {
    listen 8080;

    location /orders {
        proxy_pass http://orders:8000/;
    }
    location /users {
        proxy_pass http://users:8000/;
    }
    location / {
        return 200 'atlas demo gateway\n';
        add_header Content-Type text/plain;
    }
}
